FROM node:18-alpine

# Set work directory
WORKDIR /opt/app

# Copy package files
COPY package*.json ./

# Install dependencies
RUN npm install

# Expose port
EXPOSE 3000

# Command to run the application in development mode with hot reload
CMD ["npm", "run", "dev", "--", "--hostname", "0.0.0.0"] 